# Use an official Python runtime as a parent image
FROM python:3.11.6-slim

# Set the working directory to /app
WORKDIR /shared/src/driver

# Make port 80 available to the world outside this container
EXPOSE 5001

# Run app.py when the container launches
CMD ["python", "app.py"]